nameOverride: payment-service
fullnameOverride: payment-service

replicaCount: 2

image:
  repository: itsmot9/payment-service
  tag: latest
  pullPolicy: Always

app:
  port: 8050
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 500m

service:
  type: ClusterIP
  port: 80
  targetPort: 8050

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  ingressClassName: "nginx"
  hosts:
    - host: payment.158.160.206.47.nip.io
      paths:
        - path: /
          pathType: Prefix

env:
  PORT: "8050"
  HOST: "0.0.0.0"
  DATABASE_URL: "postgresql://program:test@postgres.rsoi-lab4.svc.cluster.local:5432/payments"
  
  KEYCLOAK_ISSUER: "http://keycloak.rsoi-lab4.svc.cluster.local:8080/realms/rsoi-realm"
  KEYCLOAK_JWKS_URI: "http://keycloak.rsoi-lab4.svc.cluster.local:8080/realms/rsoi-realm/protocol/openid-connect/certs"
  KEYCLOAK_CLIENT_ID: "lab5-client"

livenessProbe:
  httpGet:
    path: /manage/health 
    port: 8050
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /manage/health
    port: 8050
  initialDelaySeconds: 20
  periodSeconds: 5
  failureThreshold: 3
  timeoutSeconds: 3
