nameOverride: rental-service
fullnameOverride: rental-service

replicaCount: 2

image:
  repository: itsmot9/rental-service
  tag: latest
  pullPolicy: Always

app:
  port: 8060
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 500m

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  ingressClassName: "nginx"
  hosts:
    - host: rental.158.160.206.47.nip.io
      paths:
        - path: /
          pathType: Prefix

env:
  CAR_SERVICE_URL: "http://car-service:8070"
  RENTAL_SERVICE_URL: "http://rental-service:8060"
  PAYMENT_SERVICE_URL: "http://payment-service:8050"
  DATABASE_URL: "postgresql://program:test@postgres.rsoi-lab4.svc.cluster.local:5432/rentals"
  
livenessProbe:
  path: /manage/health 
  port: 8060
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /manage/health
    port: 8060
  initialDelaySeconds: 20
  periodSeconds: 5
  failureThreshold: 3
  timeoutSeconds: 3
